before:
  hooks:
    - rm -rf caddy-build
    - .github/scripts/before-hook.sh

builds:
- env:
  - CGO_ENABLED=0
  - GO111MODULE=on
  - XCADDY_SKIP_CLEANUP=1
  main: main.go
  dir: ./caddy-build
  binary: caddy
  # hooks:
  #   pre:
  #     - rm -rf caddy-build
  #     - xcaddy build --with github.com/mohammed90/caddy-ngrok-listener@latest
  #     - find . -iname 'buildenv*' -exec "mv {} caddy-build;"
  goos:
  - darwin
  # - linux
  # - windows
  # - freebsd
  goarch:
  - amd64
  # - arm
  # - arm64
  goarm:
  - "5"
  - "6"
  - "7"
  ignore:
    - goos: darwin
      goarch: arm
    - goos: freebsd
      goarch: arm
      goarm: "5"
  flags:
  - -trimpath
  - -mod=readonly
  ldflags:
  - -s -w

signs:
  - cmd: cosign
    signature: "${artifact}.sig"
    certificate: '{{ trimsuffix (trimsuffix .Env.artifact ".zip") ".tar.gz" }}.pem'
    args: ["sign-blob", "--output-signature=${signature}", "--output-certificate", "${certificate}", "${artifact}"]
    artifacts: all

sboms:
  - artifacts: binary
    documents:
      - >-
        {{ .ProjectName }}_
        {{- .Version }}_
        {{- if eq .Os "darwin" }}mac{{ else }}{{ .Os }}{{ end }}_
        {{- .Arch }}
        {{- with .Arm }}v{{ . }}{{ end }}
        {{- with .Mips }}_{{ . }}{{ end }}
        {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}.sbom
    cmd: syft
    args: ["$artifact", "--file", "${document}", "--output", "cyclonedx-json"]

archives:
  - id: default
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- if eq .Os "darwin" }}mac{{ else }}{{ .Os }}{{ end }}_
      {{- .Arch }}
      {{- with .Arm }}v{{ . }}{{ end }}
      {{- with .Mips }}_{{ . }}{{ end }}
      {{- if not (eq .Amd64 "v1") }}{{ .Amd64 }}{{ end }}


checksum:
  algorithm: sha512

release:
  github:
    owner: mohammed90
    name: caddy-ngrok-listener
  draft: true
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
    - '^chore:'
    - '^ci:'
    - '^docs?:'
    - '^readme:'
    - '^tests?:'
    - '^\w+\s+' # a hack to remove commit messages without colons thus don't correspond to a package
